[package]
name = "read-fonts-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
read-fonts = "0.1.3"
wasm-bindgen = "0.2"
js-sys = "0.3.61"